name: pytest

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: install dependencies
        run: | 
          pip install poetry
          poetry install
          make tests
      - name: code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 2b1e415e4aa4d4d253ae0e661f0b2546c98f878936ae8f4247c1ff59109533b9
        with:
          coverageCommand: make coverage
